### ISSUE TITLE
BPMN process modeler in Flow UI

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1565]
Bpmn modeler
- [x] RnD on import base `bpmn.js` modeler into `Flow Component`
- [x] RnD on JS/Java communication + **DOM event system** in `Flow Component`
- [x] Java/JS modeler component #1580
- [x] Dispatcher for BPMN's element and api for schema-read/write #1581
- [x] Migrate modeler BPMN's element propreties palette #1582
- [x] Bpmn Viewer #1772

Features:
- `Modeler` JS/Java component 
-  Migrate "classic" featured `bpmn element properties palette`
- `Viewer` JS/Java component

In development:
- `DMN` integration into BPMN
- `Drafts` in modeler

Authors:
- @KartnDev 
- @KremnevDmitry

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5305-231
IntelliJ version: IntelliJ IDEA 2023.1.3 (Ultimate Edition)
