### ISSUE TITLE
[BPMN Modeler in FlowUI] Add Mdoeler's Inspection components

### ISSUE THREAD

**Issue by KartnDev** [jmix-framework/jmix#1582]
### High level inspection:

- [ ] Add mapping jmix ui component -> selected bpmn 2.0 component
- [ ] Add list of inspection ui components

#### 1. Event

- [ ] bpmnStartEvent
- [ ] bpmnStartEvent + bpmnMessageEventDefinition
- [ ] bpmnStartEvent + bpmnTimerEventDefinition
- [ ] bpmnStartEvent + bpmnConditionalEventDefinition
- [ ] bpmnStartEvent + bpmnSignalEventDefinition

- [ ] bpmnIntermediateThrowEvent
- [ ] bpmnIntermediateThrowEvent+ bpmnMessageEventDefinition
- [ ] bpmnIntermediateThrowEvent + bpmnEscalationEventDefinition
- [ ] bpmnIntermediateThrowEvent + bpmnLinkEventDefinition
- [ ] bpmnIntermediateThrowEvent + bpmnCompensateEventDefinition
- [ ] bpmnIntermediateThrowEvent + bpmnSignalEventDefinition

- [ ] bpmnIntermediateCatchEvent
- [ ] bpmnIntermediateCatchEvent + bpmnMessageEventDefinition
- [ ] bpmnIntermediateCatchEvent + bpmnTimerEventDefinition
- [ ] bpmnIntermediateCatchEvent+ bpmnConditionalEventDefinition
- [ ] bpmnIntermediateCatchEvent + bpmnLinkEventDefinition
- [ ] bpmnIntermediateCatchEvent + bpmnSignalEventDefinition

- [ ] bpmnEndEvent
- [ ] bpmnEndEvent + bpmnMessageEventDefinition
- [ ] bpmnEndEvent + bpmnEscalationEventDefinition
- [ ] bpmnEndEvent + bpmnErrorEventDefinition
- [ ] bpmnEndEvent + bpmnCancelEventDefinition,
- [ ] bpmnEndEvent + bpmnCompensateEventDefinition,
- [ ] bpmnEndEvent + bpmnSignalEventDefinition,
- [ ] bpmnEndEvent + bpmnTerminateEventDefinition

#### 2. Gateways

- [ ] bpmnExclusiveGateway
- [ ] bpmnParallelGateway
- [ ] bpmnInclusiveGateway
- [ ] bpmnComplexGateway
- [ ] bpmnEventBasedGateway

#### 3. Tasks

- [ ] bpmnTask
- [ ] bpmnUserTask
- [ ] bpmnServiceTask
- [ ] bpmnSendTask
- [ ] bpmnReceiveTask
- [ ] bpmnManualTask
- [ ] bpmnBusinessRuleTask
- [ ] bpmnScriptTask
- [ ] bpmnCallActivity

#### 4. SubProcess

- [ ] bpmnSubProcess
- [ ] bpmnTransaction
- [ ] bpmnSubProcess + collapsed = CollapsedSubProcess
- [ ] bpmnSubProcess + triggeredByEvent = EventSubProcess

#### 5. Domain

- [ ] bpmnDataObjectReference
- [ ] bpmnDataStoreReference

#### 6. IAM

- [ ] bpmnParticipant
- [ ] bpmnGroup

#### 7. Misc
- [ ] Link and Lines
- [ ] Shapes
- [ ] Labels
