### ISSUE TITLE
BPM flowui improvements

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#1961]
#### TODO
- [x] #1962
- [x] Notifications: Process definitions view-> Migrate all instances -> "Instances migrated" notification
- [x] Selects are not validated on forms which allows to start process without required parameters (wrong components)
- [x] "bpm_ProcessDefinitionData.lookup" view
- [x] Copyrights, javadocs, additional logging, etc.

#### QA Notes:

- Check that  "Process instances migrated"  notification appears after "Process definitions view-> Migrate all instances " view closed with confirmation.
- Create required enum, platformEnum fields for process form and make sure they highlighted as required on form.
- Check that Called element for Call activity form selected through simple process definition lookup:

![Image](https://github.com/jmix-framework/jmix/assets/38808384/c2bfcbb7-cd11-4190-9f4c-664934ebe0f7)
