### ISSUE TITLE
Maps add-on improvements

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#2435]
### Tasks
- [x] https://github.com/jmix-framework/jmix/issues/2576
- [x] https://github.com/jmix-framework/jmix/issues/2790
- [x] #2575
- ~~Feature Drag and Drop~~ (moved to https://github.com/jmix-framework/jmix/issues/2832)
- [x] #2719
- [x] #2704
- [x] https://github.com/jmix-framework/jmix/issues/2807
- [x] #2735
- [x] https://github.com/jmix-framework/jmix/issues/2824

Research ability to change Data Binding
- [x] - Use not only one `@Geometry` property (Deprecated)
- [x] - Use specified property for showing geo-objects. Also, see https://github.com/jmix-framework/jmix/issues/1216
