### ISSUE TITLE
Ability to edit features on the Map

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#2832]
### Feature Description

The main idea is to add the mode or something else to enable editing/creating geometries that is bound with JPA entities. It will enable to users work with geometries not as text in field (which is almost impossible for simple users) but with the Map, where they can move geometry, change lines, etc.

In OpenLayers it is possible to draw and edit geometries: https://openlayers.org/en/latest/examples/draw-and-modify-features.html

Additionally, provide layer selection ability. For instance, when a map has 2 layers with features and we need to edit only features from one layer. So other features should be "static".

Upd. 
1) Feature drawing will be implemented in https://github.com/jmix-framework/jmix/issues/4175
2) Instead of "layer selection" it is possible to change `featureDragEnabled` and `featureModifyEnabled` attributes in sources to limit features editing.

### Tasks
The editable map should include the following features:
- [x] - ~Layers~ Source:
   - [x] - feature selection option. Enables to select features within layer.
   - [x] - feature draggable option. Enables feature moving within layer. 
   - [x] - feature modifiable option. Enables feature modifying within layer.
- [x] - Selection events
- [x] - Dragging events
- [x] - Modifying events
- [x] - Deleting events
- In general, there will be 3 tools (like modes) for editing:
   - [x] - Dragging
   - [X] - Modifying. Also contains vertices deletion.
   - [x] - Deleting. The object deletion should set `null` for bounded property.
- [x] - Localization for new messages.
- [x] - Tooltips for modes.
- [ ] - Cursors for modes.

## Changes
The `VectorSource` and `DataVectorSource` in the Map component support three feature modes:
1) Select mode
2) Drag mode
3) Modify mode

### Select mode
Allows users to select features on a map. To enable this mode, use `featureSelectEnabled` attribute in XML:
```
<maps:geoMap id="map" height="100%" width="100%">
    <maps:layers>
        <maps:tile>
            <maps:osmSource/>
        </maps:tile>
        <maps:vector id="layer">
            <maps:vectorSource id="source" featureSelectEnabled="true"/>
        </maps:vector>
        <maps:vector id="geoObjectVector">
            <maps:dataVectorSource id="geoObjectSource" featureSelectEnabled="true" dataContainer="cityDistrictsDc" property="area"/>
        </maps:vector>
    </maps:layers>
</maps:geoMap>
```

![Image](https://github.com/user-attachments/assets/ea3a60da-d681-4938-9298-b50e71496056)

In Java code, new interfaces are provided:
- `HasFeatureSelect` for feature objects
- `HasGeoObjectSelect` for working with data containers

They provide an API for programming selection and deselection of objects. Additionally, there are events for handling selection and deselection:
- `SourceFeatureSelectEvent`
- `SourceGeoObjectSelectEvent`

Example of selecting feature programmatically:
```
@ViewComponent("map.vector.source")
private VectorSource source;

@Subscribe("doButton")
public void onDoButtonClick(ClickEvent<JmixButton> event) {
    source.selectFeature(feature);
}
```
Example of listening an event:
```
@Subscribe("map.vector.source")
public void onMapVectorSourceSourceFeatureSelection(final HasFeatureSelect.SourceFeatureSelectEvent event) {
    notifications.create("GeoObjectSelectEvent", "Selected: %s,\nDeselected: %s" .formatted(
                    event.getSelected().size(), event.getDeselected().size()))
            .withPosition(Notification.Position.BOTTOM_END)
            .show();
}
```
### Drag mode
Allows users to drag objects on a map. When this mode is enabled in at least one source, the map will display a button that indicates whether drag mode is active. To enable this mode, use the `featureDragEnabled` attribute in XML.
```
<maps:geoMap id="map" height="100%" width="100%">
    <maps:layers>
        <maps:tile>
            <maps:osmSource/>
        </maps:tile>
        <maps:vector id="layer">
            <maps:vectorSource id="source" featureDragEnabled="true"/>
        </maps:vector>
        <maps:vector id="geoObjectVector">
            <maps:dataVectorSource id="geoObjectSource" featureDragEnabled="true" dataContainer="cityDistrictsDc" property="area"/>
        </maps:vector>
    </maps:layers>
</maps:geoMap>
```
![Image](https://github.com/user-attachments/assets/fc21dd3d-69a4-4264-a03c-ae6b1a5f511e)

In Java code, new interfaces are provided:
- `HasFeatureDrag` for feature objects
- `HasGeoObjectDrag` for working with data containers

They provide events for handling:
- Drag start
- Drag end

For instance:
```
@Subscribe("map.vector.source")
public void onSourceFeatureDragStart(HasGeoObjectDrag.SourceGeoObjectDragStartEvent<CityDistrict> event) {
    notifications.create("SourceGeoObjectDragStartEvent")
            .withPosition(Notification.Position.BOTTOM_END)
            .show();
}

@Subscribe("map.vector.source")
public void onDSourceFeatureDragEnd(HasGeoObjectDrag.SourceGeoObjectDragEndEvent<CityDistrict> event) {
    notifications.create("SourceGeoObjectDragEndEvent")
            .withPosition(Notification.Position.BOTTOM_END)
            .show();
}
```
### Modify mode
Modify mode allows users to change vertex positions, delete vertices, and delete features. When this mode is enabled in at least one source, the map will display two buttons:
 - A button that enables vertex modification.
 - A button that enables feature deletion.

To enable this mode, use the `featureModifyEnabled` attribute in XML.
```
<maps:geoMap id="map" height="100%" width="100%">
    <maps:layers>
        <maps:tile>
            <maps:osmSource/>
        </maps:tile>
        <maps:vector id="layer">
            <maps:vectorSource id="source" featureModifyEnabled="true"/>
        </maps:vector>
        <maps:vector id="geoObjectVector">
            <maps:dataVectorSource id="geoObjectSource" featureModifyEnabled="true" dataContainer="cityDistrictsDc" property="area"/>
        </maps:vector>
    </maps:layers>
</maps:geoMap>
```
![Image](https://github.com/user-attachments/assets/d13e6a07-726a-4cbc-b0a8-50ed0d33dda0)

In Java code, new interfaces are provided:
 - `HasFeatureModify` for feature objects
 - `HasGeoObjectModify` for working with data containers

These interfaces provide events for handling:
 - Modify start
 - Modify end

Additionally, `HasFeatureModify` provides a delete event.

Example of handling modify events:
```
@Subscribe("map.vector.source")
public void onMapVectorSourceModifyStart(SourceGeoObjectModifyStartEvent<CityDistrict> event) {
    notifications.create("ModifyStart")
            .withPosition(Notification.Position.BOTTOM_END)
            .show();
}

@Subscribe("map.vector.source")
public void onMapVectorSourceModifyEnd(SourceGeoObjectModifyEndEvent<CityDistrict> event) {
    notifications.create("ModifyEnd")
            .withPosition(Notification.Position.BOTTOM_END)
            .show();
}
```

**Comment by enimiste** [comment]
Thank you a lot. This is awesome work.
My dream released ❤️❤️❤️
is will be included in which Jmix version ?

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.5.999-SNAPSHOT
Jmix Studio Plugin Version: 2.5.SNAPSHOT7205-243
IntelliJ version: IntelliJ IDEA 2024.3.3 (Community Edition)
