### ISSUE TITLE
Condition and repository improvements. Part II

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#2934]
In the continuation of jmix-framework/jmix#2490

#### Tasks:

- [x] Refactoring and misc improvements
- [x] Check corner cases of jmix-framework/jmix#2490
- [x] Cover them with autotests

#### QA Notes:
Covered by autotests
