### ISSUE TITLE
Support for JPA cascade operations

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#358]
## Progress
- [x] (2d)R&D
- [x] (7d) Callback-based implementation (rejected)
- [x] (8d) Jmix-only cascade processing Implementation
    - [x] (1d) Cascade type metadata
    - [x] (2d) DataManager cascade operations
    - [x] (5d) Recheck and implement if need
        - [x] (2d) Events
        - [x] (4h) Dynamic attributes
        - [x] (4h) Entity Log
        - [x] (4h) Soft deletion (in case fo absence `@OnDelete`/`@OnDeleteInerse`)
        - [x] (4h) Constraints (e.g. constraint cascade deletion of entity when it is prohibited)
        - [x] (4h) Cross-datastore logic????
- [x] (2d) Tests

## Result:
Jpa cascade operations support has been implemented for `DataManager`. 
Operations `DataManager#save()` and `DataManager#remove()` will be applied to related entities according to `cascade` property of annotations: `@OneToOne`,`@OneToMany`,`@ManyToOne`, `@ManyToMany`.

Following mechanisms will be triggered for cascade processed entities in addition to standard JPA saving (persisting or merging) and removing:
- Events
- Dynamic attributes
- Entity Log
- Security Constraints
- Cross-Datastore references

SoftDeletion works independently from cascade operations and uses it's own annotations.

**Warning:** CascadeType.PERSIST will lead to persisting entity by eclipselink even if this entity is already persisted in db. So do not use PERSIST cascade type with editors that open lookup screens which allows to create and save new entity before selecting it.

## QA Notes:
Most of use cases covered by autotests, there are few to test manually:
### Part I
1. Open and run project [ctest.zip](https://github.com/jmix-framework/jmix/files/8676808/ctest.zip)
3. Сreate "Parent" and related "Child" entity instances
4. Open Parent Browser (without opening editor!) and remove parent.
5. **ER:** Child entities removed too
### Part II
1. Make sure Entity Log set up for "Parent" and "Child" entity 
2. Сreate "Parent" and related "Child" entities - make sure entity log records present for both entity types
3. Open Parent Browser, press button "Modify Names (Test Part II)"
4. **ER:** "[UPD]" postfix should appear in names of Child entities as for Parent
5. Open Entity logs for Child entity 
6. **ER:** there are log records about modifying properties `Child.name` for Child entities
7. Open Child in Entity Inspector
8. **ER:** "Created Date", "Created By", "Last Modified Date", "Last Modified By" properties should contain correct values

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2022.1.1 (Ultimate Edition)
io.jmix.studio (1.3.SNAPSHOT4250-213)
jmix version (1.3.999-SNAPSHOT)
