### ISSUE TITLE
GenericFilter component

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#837]
Generic Filter

- [x] Component
- [x] Actions
- [x] XML + Loader
- [ ] Flexible layout definition (https://github.com/jmix-framework/jmix/issues/1443)
- [x] JavaDoc
- [x] Polishing

Property Filter

- [x] Component
- [x] Fields Generation Strategy
- [x] XML + Loader
- [ ] Date Interval Operation (https://github.com/jmix-framework/jmix/issues/1442)
- [ ] In Operation (requires https://github.com/jmix-framework/jmix/issues/1044, https://github.com/jmix-framework/jmix/issues/1442)
- [x] JavaDoc
- [x] Polishing

JpqlFilter

- [x] Component
- [x] Fields Generation Strategy
- [ ] XML + Loader (posponed, used only in GenericFilter)
- [x] JavaDoc
- [x] Polishing

Group Filter
- [x] Component
- [x] JavaDoc
- [x] Polishing

Other
- [x] Kit part?

#### PropertyFilter - new component

Same as UI Classic, but without `IN` and `INTERVAL` operations (https://github.com/jmix-framework/jmix/issues/1442).

#### GenericFilter - new component

Limited functionality:
* Runtime only
* No custom configurations
* Add condition - supports only predefined conditions based on entity attributes
* Clear action
