### ISSUE TITLE
Security UI

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#838]
### Done
A lot

### ToDo

- [x] Add Read action
- [x] Fix View options
- [ ] Check unsaved changes
